title: "Starforged Documentation"
author:
  name: Starforged Team
  email: ""

description: >-
  Documentation for the 4th iteration of Starforged

copyright_notice: "© 2024 Starforged Team. All Rights Reserved."

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - docs/installation/index.md
  - docs/modlist/index.md
  - posts.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: false

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  date_format: "%b-%d-%Y"
  social-links:
    - {
        title: "Github",
        platform: github,
        user_url: "https://github.com/StarforgedSMP",
      }
