title: "Starforged Documentation"
author:
  name: NotAShelf
  email:

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Documentation for the 4th iteration of Starforged

# If you clone the Minima repo and build locally, use this setting.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - docs/installation/index.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: dark
  date_format: "%b-%d-%Y"
  social_links:
    - {
        platform: github,
        user_url: "https://github.com/StarforgedSMP/Starforged4",
      }
