name = "STARFORGED 4"
author = "STARPLANET"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86177d7cd56db0ceac79588d023f31ed37fa41a5b9badf7930c5dc8c9602a224"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
