name = "STARFORGED 4"
author = "STARPLANET"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2db3972a391980718bf60102b604b3786f06f486b719c17b8bf9b1ef6218f4fb"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
