name = "STARFORGED 4"
author = "STARPLANET"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93de65129aff768fa80979174e208544d7910c83b03475af241df0d74e0a9d89"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
