name = "STARFORGED 4"
author = "STARPLANET"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "593b919422e3d45de83335133186a08861825b8fe28f91d89c2de368eccd519a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
