name = "STARFORGED 4"
author = "STARPLANET"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "529366692bbd679dba2bdebafa523e0b444bc7c3cf724f8985e40016c427b09a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
