name = "STARFORGED 4"
author = "STARPLANET"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78182b67a4e91a1f4dba4f5f59f97f2b5f0476534650076d7e08a9978e661e63"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
