name = "STARFORGED 4"
author = "STARPLANET"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a64b18723b7758ab6faeb4ace42d3262048b5ed03324837be6f477b8f4c786c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
