name = "STARFORGED 4"
author = "STARPLANET"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b01476add701d7f5807c19c6084fa3f8358c5cd5309d37cef4572fad1526a5c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
