name: Publish Modpacks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  publish-modpacks:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install packwiz
        run: nix profile install nixpkgs#packwiz

      - name: Export Curseforge & Modrinth Profiles
        run: |
          # Move to the packwiz configuration root
          cd packwiz

          # Platform specific exports
          packwiz modrinth export --output "../Starforged4-1.20.1-modrinth.zip"
          packwiz curseforge export --output "../Starforged4-1.20.1-curseforge.zip"

      - name: Generate Prismlauncher Profile
        run: |
          nix run .#packwiz-installer-bootstrap -- -g https://starforgedsmp.github.io/Starforged4/packwiz/pack.toml -s both

          # Fetch mods using the installer-bootstrap to generate Prismlauncher
          # profile.
          zip -r "Starforged4-1.20.1-prismlauncher-zip" \
            config mods intex.toml pack.toml \
            instance.cfg mmc-pack.json starforged_4_icon.png \
            packwiz-installer-bootstrap.jar

      - name: Generate "Generic" Pack
        run: |
          nix run .#packwiz-installer-bootstrap -- -g https://starforgedsmp.github.io/Starforged4/packwiz/pack.toml -s both

          # Fetch mods using the installer-bootstrap to generate
          # "generic" pack with minimal dependencies
          zip -r "Starforged4-1.20.1-generic.zip" \
            mods config

      - name: Get current date
        id: get-date
        # output format: 2023-12-30-234559
        run: echo "date=$(date +'%Y-%m-%d-%H%M%S')" >> "${GITHUB_OUTPUT}"

      - name: Packs-release-{{ github.sha }}
        uses: softprops/action-gh-release@v2
        with:
          name: "Starforged4 Modpacks (Rev: ${{ steps.get-date.outputs.date }})"
          tag_name: "${{ steps.get-date.outputs.date }}"
          files: |
            Starforged4-1.20.1-modrinth.zip
            Starforged4-1.20.1-curseforge.zip
            Starforged4-1.20.1-generic.zip
            Starforged4-1.20.1-prismlauncher.zip

          body: |
            # Automatic Modpack Releases

            - Built on: ${{ steps.get-date.outputs.date }}
            - Revision: ${{ github.sha }}

            [Installation]: https://starforgedsmp.github.io/Starforged4/docs/installation/

            This automated workflow will generate modpack archives (indicated by the target
            of the pack in the filename) for **Modrinth**, **Curseforge** and **Prismlauncher**.

            If you use a supported launcher with importing capabilities for packs of above formats, you
            may consider downloading the appropriate pack for your launcher. Please take a look at
            [the documentation](installation) for tips specific to your launcher.

            For users without compatible launchers, or for those that want a more hands-on approach to
            their mod management, a "generic" archive is generated. The generic pack will contain ONLY
            the `mods` and `config` directories, leaving the installation to your own hands.
